# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: MiTeC.SystemInformationX
PackageVersion: "1"
PackageLocale: en-US
Publisher: MiTeC
PackageName: SystemInformationX
License: Free to use for private, educational and non-commercial purposes.
ShortDescription: Full-featured system information about your system.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
