# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: TranslucentTB.TranslucentTB
PackageVersion: "2024.1"
PackageLocale: en-US
Publisher: TranslucentTB
PackageName: TranslucentTB
License: GPL-3.0 License
ShortDescription: A lightweight utility that makes the Windows taskbar translucent/transparent.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
