# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: LibreWolf.LibreWolf
PackageVersion: 123.0-1
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
    MinimumVersion: 14.28.29913.0
Installers:
- Architecture: x86
  InstallerUrl: https://gitlab.com/api/v4/projects/44042130/packages/generic/librewolf/124.0.1-1/librewolf-124.0.1-1-windows-x86_64-setup.exe
  InstallerSha256: C8A97DD57AC10928DB8D5840358B4C8C4B51CA638348F1146E49A74782F042D5
ManifestType: installer
ManifestVersion: 1.6.0
